spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/fogostore_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: ${PORT:5004}
  ssl:
    key-store: C:\Users\Admin\Desktop\project\fogostore\ssl\20230501\fogostore_vn.p12
    key-store-password: Fogostore@123
    key-alias: fogostorevn
    key-store-type: PKCS12
    key-password: Fogostore@123
    enabled: false
image_folder_path: C:\Users\Admin\Desktop\project\fogostore\images
sitemap_location: C:\Users\Admin\Desktop\project\fogostore\sitemap
web_domain: http://localhost:5004
---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://45.122.221.212:3306/fogostore_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: fogostoreWebApiClient
    password: Fogostore@2321998
server:
  port: ${PORT:443}
  ssl:
    key-store: /deployments/fogostore/ssl/20230501/fogostore_vn.p12
    key-store-password: Fogostore@123
    key-alias: fogostorevn
    key-store-type: PKCS12
    key-password: Fogostore@123
    enabled: true
image_folder_path: /deployments/fogostore/images
sitemap_location: /deployments/fogostore/sitemap
web_domain: https://fogostore.vn
